Traceback (most recent call last):
  File "/home2/longxin/ls/envs/jupyterlab-ext/lib/python3.9/site-packages/transformers/configuration_utils.py", line 133, in from_pretrained
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)
  File "/home2/longxin/ls/envs/jupyterlab-ext/lib/python3.9/site-packages/transformers/file_utils.py", line 182, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file distilbert-base-uncased-finetuned-sst-2-english not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/longxin/Neural_Coder_EXT/tmp.py", line 26, in <module>
    my_nlp_model = AutoModelForSequenceClassification.from_pretrained(
  File "/home2/longxin/ls/envs/jupyterlab-ext/lib/python3.9/site-packages/transformers/modeling_auto.py", line 385, in from_pretrained
    return DistilBertForSequenceClassification.from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home2/longxin/ls/envs/jupyterlab-ext/lib/python3.9/site-packages/transformers/modeling_utils.py", line 283, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home2/longxin/ls/envs/jupyterlab-ext/lib/python3.9/site-packages/transformers/configuration_utils.py", line 145, in from_pretrained
    raise EnvironmentError(msg)
OSError: Model name 'distilbert-base-uncased-finetuned-sst-2-english' was not found in model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad). We assumed 'distilbert-base-uncased-finetuned-sst-2-english' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.
